### ISSUE TITLE
Creating new layout condition for first layout doesn't work

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#169]
### Steps to reproduce
1. Open All layout conditions tab.
2. Click New Condition button.
3. Click create layout condition.

### Expected result
Condition should be created.
### Actual result
```
System.ArgumentException: ScErrBadArguments (SCERR1001): One or more arguments was invalid. Encoded string of ObjectID is of invalid size
Version: 2.4.0.5764.
Help page: https://docs.starcounter.io/?q=SCERR1001.
   at Starcounter.DbHelperImpl.Base64DecodeObjectID(String objectID)
   at Starcounter.Db.FromId[T](String base64Id) in C:\TeamCity\BuildAgent\work\sc-17142\Level1\src\Starcounter\Db.cs:line 49
   at BlendingEditor.Website.ViewModels.AllLayoutConditionsPage.Handle(CreateModalTrigger action) in C:\
epositories\Blending\src\BlendingEditor\Website\ViewModels\AllLayoutConditionsPage.json.cs:line 63
   at lambda_method(Closure , Json , Input`1 )
   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action)
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value)
   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, String valueStr)
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-17142\Level1\src\Starcounter\TransactionManager.cs:line 557
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-17142\Level1\src\Starcounter\Transaction.cs:line 233
   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action)
   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value)
   at Starcounter.XSON.JsonPatch.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection, JsonPatchStatus previousStatus)
   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount)
   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount)
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-17142\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 75
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-17142\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 290
   at Starcounter.GatewayHandlers.<>c__DisplayClass18_1.<HandleWebSocket>b__0() in C:\TeamCity\BuildAgent\work\sc-17142\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 791
   at Starcounter.Session.Use(Action action)
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-17142\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 790
HResult=-2147024809
HelpLink=https://docs.starcounter.io/?q=SCERR1001
```

**Comment by PatrykSzwer** [comment]
Fix for that was included in https://github.com/Starcounter/Blending/commit/d8e3ccd6b8a090eb78a2b0a92606d0b5ebbff4ac

It can be removed after https://github.com/Juicy/juicy-select/issues/22 is done, but for now, this issue is fixed.
