### ISSUE TITLE
TeamCity tests for Blending are falling.

### ISSUE THREAD

**Issue by kegor** [Starcounter/Blending#258]
### Steps to reproduce
Run build in `Blending` repo on the `master` branch.

### Expected result
Tests passed.

### Actual result
Tests are falling.

##### Starcounter version 
2.4.990.117

##### Involved apps' version
 - BlendingEditor@6.4.0
 - BlendingProvider@6.4.0
 
##### Browsers affected
- [x] Chrome
- [x] Firefox

### Notes
- Tests passed locally.
- `master` branch in the `Blending` repo now has all changes from the `mapping` branch of the same repo.
- the first TC build with such kind of problem https://teamcity.starcounter.org/viewLog.html?buildId=60426&tab=buildResultsDiv&buildTypeId=Apps_Blending_BlendingMasterWithStarcounterDevelop24
- typical error looks like:
```
OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:4444/wd/hub/session timed out after 60 seconds.
  ----> System.Net.WebException : The operation has timed out
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at BlendingEditor.Tests.Utilities.WebDriverManager.StartDriver(Browser browser, TimeSpan timeout, Uri remoteWebDriverUri) in C:\TeamCity\BuildAgent\work\1ee82139cef36e7f\Blending\test\BlendingEditor.Tests\Utilities\WebDriverManager.cs:line 19
   at BlendingEditor.Tests.Test.BaseTest.TestFixtureSetUp() in C:\TeamCity\BuildAgent\work\1ee82139cef36e7f\Blending\test\BlendingEditor.Tests\Test\BaseTest.cs:line 47
--WebException
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
```

**Comment by kegor** [comment]
Closing because the issue was moved in https://github.com/Starcounter/AdminTrack/issues/558.
