### ISSUE TITLE
Export crashes after deleting a layout condition

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#270]
### Steps to reproduce

1. Go to the all layout conditions page
2. Create some layout conditions
3. Delete one layout condition
4. Go to settings page
5. Click on Export

### Expected result

The export file should be generated

### Actual result

There is an exception:

```
PalindromConnectionError: Server error
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at BlendingEditor.Migration.MigrationClasses.WebHttpHeaderMigration.Populate(WebHttpHeader webHttpHeader) in C:\www\HeadsOmni\src\Blending.Mapper\Blending\src\BlendingEditor\Migration\MigrationClasses\WebHttpHeaderMigration.cs:line 22
	   at BlendingEditor.Migration.JsonMigrationContainer.PopulateForExport() in C:\www\HeadsOmni\src\Blending.Mapper\Blending\src\BlendingEditor\Migration\JsonMigrationContainer.cs:line 88
	   at BlendingEditor.Website.Helpers.MigrationHelper.ExportDataToFile(String& message) in C:\www\HeadsOmni\src\Blending.Mapper\Blending\src\BlendingEditor\Website\Helpers\MigrationHelper.cs:line 19
	   at BlendingEditor.Website.ViewModels.SettingsPage.ExportToJsonFile() in C:\www\HeadsOmni\src\Blending.Mapper\Blending\src\BlendingEditor\Website\ViewModels\SettingsPage.json.cs:line 121
	   at BlendingEditor.Website.ViewModels.SettingsPage.Handle(ExportDataTrigger action) in C:\www\HeadsOmni\src\Blending.Mapper\Blending\src\BlendingEditor\Website\ViewModels\SettingsPage.json.cs:line 100
	   at BlendingEditor.Website.ViewModels.SettingsPage.JsonByExample.Schema.<>c.<.ctor>b__0_57(Json pup, Input`1 input)
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action)
	   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value)
	   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, String valueStr)
	   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\tc_work\sc-19141\Level1\src\Starcounter\TransactionManager.cs:line 557
	   at Starcounter.Transaction.Scope(Action action) in C:\tc_work\sc-19141\Level1\src\Starcounter\Transaction.cs:line 233
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action)
	   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value)
	   at Starcounter.XSON.JsonPatch.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection, JsonPatchStatus previousStatus)
	   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount)
	   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount)
	   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\tc_work\sc-19141\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 73
	   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\tc_work\sc-19141\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
	   at Starcounter.GatewayHandlers.<>c__DisplayClass18_1.<HandleWebSocket>b__0() in C:\tc_work\sc-19141\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 780
	   at Starcounter.Session.Use(Action action)
	   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\tc_work\sc-19141\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 779

	   at BlendingEditor.Migration.MigrationClasses.WebHttpHeaderMigration.Populate(WebHttpHeader webHttpHeader) in C:\www\HeadsOmni\src\Blending.Mapper\Blending\src\BlendingEditor\Migration\MigrationClasses\WebHttpHeaderMigration.cs:line 22
	   at BlendingEditor.Migration.JsonMigrationContainer.PopulateForExport() in C:\www\HeadsOmni\src\Blending.Mapper\Blending\src\BlendingEditor\Migration\JsonMigrationContainer.cs:line 88
	   at BlendingEditor.Website.Helpers.MigrationHelper.ExportDataToFile(String& message) in C:\www\HeadsOmni\src\Blending.Mapper\Blending\src\BlendingEditor\Website\Helpers\MigrationHelper.cs:line 19
	   at BlendingEditor.Website.ViewModels.SettingsPage.ExportToJsonFile() in C:\www\HeadsOmni\src\Blending.Mapper\Blending\src\BlendingEditor\Website\ViewModels\SettingsPage.json.cs:line 121
	   at BlendingEditor.Website.ViewModels.SettingsPage.Handle(ExportDataTrigger action) in C:\www\HeadsOmni\src\Blending.Mapper\Blending\src\BlendingEditor\Website\ViewModels\SettingsPage.json.cs:line 100
	   at BlendingEditor.Website.ViewModels.SettingsPage.JsonByExample.Schema.<>c.<.ctor>b__0_57(Json pup, Input`1 input)
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action)
	   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value)
	   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, String valueStr)
	   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\tc_work\sc-19141\Level1\src\Starcounter\TransactionManager.cs:line 557
	   at Starcounter.Transaction.Scope(Action action) in C:\tc_work\sc-19141\Level1\src\Starcounter\Transaction.cs:line 233
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action)
	   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value)
	   at Starcounter.XSON.JsonPatch.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection, JsonPatchStatus previousStatus)
	   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount)
	   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount)
	   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\tc_work\sc-19141\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 73
	   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\tc_work\sc-19141\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
	   at Starcounter.GatewayHandlers.<>c__DisplayClass18_1.<HandleWebSocket>b__0() in C:\tc_work\sc-19141\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 780
	   at Starcounter.Session.Use(Action action)
	   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\tc_work\sc-19141\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 779
    at WebSocket._ws.onmessage (http://backoffice.omni.local/sys/Palindrom/dist/palindrom-dom.min.js:14:3691)
```

##### Involved apps' version

Blending 4b591625a8aa7dd0f80b8a1de1be43c371a6d034
 
##### Browsers affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari

**Comment by warpech** [comment]
Fixed in #272
