### ISSUE TITLE
⏰JsonPatchException: Unsupported patch operation in patch when saving composition

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#30]
### Steps to reproduce
1. Run Blending app and People app.
2. do `/blendingeditor/resetdata`
3. Go to `/people/persons`
4. Turn on compositionEditor (Ctrl + E)
5. Select `[slot="blendingeditor/Main"]` from editor dropdown.
6. Change anything in the composition (e.g add some text on the end)
7. Click save.
### Expected result
No errors, composition is saved.
### Actual result
Exception:
```
Starcounter.XSON.JsonPatch.JsonPatchException: Unsupported patch operation in patch: 'Add'. Patch: '{"op":"add","path":"/BlendingProvider_0/Sections/Main/BlendingProvider_0/Composition$","value":"<style>:host{display:block}</style>\
        <slot name=\"BlendingProvider/SurfaceCachedActive\"></slot>\
    <slot></slot>ss"}'. Viewmodel versions: {client (_ver#c$): 1, clients serverversion: 0, server (_ver#s): 0}.
   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 17
   at Starcounter.XSON.JsonPatch.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection, JsonPatchStatus previousStatus) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 603
   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 524
   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 414
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 73
Patch={"op":"add","path":"/BlendingProvider_0/Sections/Main/BlendingProvider_0/Composition$","value":"<style>:host{display:block}</style>\
        <slot name=\"BlendingProvider/SurfaceCachedActive\"></slot>\
    <slot></slot>ss"}
Severity=1
HResult=-2146233088
```
### Additional informations

I'm getting errors in console like this really often:
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    at Function.window.Polymer._polymerFn (http://localhost:8080/sys/polymer/lib/legacy/polymer-fn.html:44:22)
    at window.Polymer (http://localhost:8080/sys/polymer/lib/utils/boot.html:29:27)
    at <anonymous>:2:9
    at HTMLElement.StarcounterIncludePrototype.stampComposition (http://localhost:8080/sys/starcounter-include/starcounter-include.html:491:28)
    at HTMLElement.StarcounterIncludePrototype._renderCompositionChange (http://localhost:8080/sys/starcounter-include/starcounter-include.html:216:26)
    at HTMLElement.StarcounterIncludePrototype.updateComposition (http://localhost:8080/sys/starcounter-include/starcounter-include.html:253:29)
    at HTMLElement.StarcounterIncludePrototype._compositionChanged (http://localhost:8080/sys/starcounter-include/starcounter-include.html:239:25)
    at HTMLElement.aceChanged (http://localhost:8080/sys/starcounter-layout-html-editor/starcounter-layout-html-editor.html:248:34)
    at HTMLElement.handler (http://localhost:8080/sys/polymer/lib/mixins/template-stamp.html:92:28)
    at Array.<anonymous> (http://localhost:8080/sys/juicy-ace-editor/juicy-ace-editor.html:100:29)
```
e.g when I change `[partial-id="/blendingprovider/surface/Key/html"]` composition (during change, but after save everything is working, if previous exception is not raised).

CC: @tomalec

**Comment by tomalec** [comment]
Seems like something related to https://github.com/Starcounter/Blending/pull/3

**Comment by PatrykSzwer** [comment]
Trough further investigation, turns out that problem happens to slots from surface itself, not slots from app. E.g I've tried to reproduce this problem with people app. People app provides one starcounter-include possible to edit from CompositionEditor - current-page. And editing and saving this one is working perfectly:
![repro](https://user-images.githubusercontent.com/25042256/35149827-dd6b2700-fd17-11e7-911c-24cf7a5816e4.gif)

**Comment by tomalec** [comment]
I would suspect this is something regarding the way new Blending (instead of CompositionProvider) provides namespace with composition.

**Comment by warpech** [comment]
Tomek suspects that BlendingProvider does not attach the view-model property with a custom composition for a layout.

@kegor pls try to reproduce and find a solution. I and @un-tone can help with that.

**Comment by kegor** [comment]
On my view problem here can be related to the following:
1. On [these lines in level1](https://github.com/Starcounter/level1/blob/2d6990034e47906453c8108c6191bdf43aa78959/src/Starcounter.XSON/Sessions/JSON-Patch/DefaultPatchHandler.cs#L16-L17) I see that JsonPatchException is thrown when patch operation does not equal to `Replace`:
```csharp
   if (patchOp != JsonPatchOperation.Replace)
       throw new JsonPatchException(1, "Unsupported patch operation in patch: '" + patchOp.ToString() + "'.");
```

2. And while reproducing I see that after click `Save` button patch operation with value `add` is performing:
![image](https://user-images.githubusercontent.com/17431807/36480091-175de10a-171c-11e8-9f5f-d236a064b63c.png)

@warpech, @PatrykSzwer could you please help me with sharing your view on the next steps for this bug? For me, it looks reasonable to change `add` to `replace` for such operations but I'm not so familiar with CompositionEditor patch operations ideology.

**Comment by warpech** [comment]
Client side produces the `add` operation when it cannot find the path in the observed view-model.

It seems that the changes in `Composition$` are detected and sent to the server when the object `/BlendingProvider_0/Sections/Main/BlendingProvider_0` is not available anymore or when it does not have the property `Composition$`.

Does it help to push the investigation further?

**Comment by kegor** [comment]
As a result of the long discussion with Anton I finished with this commit (https://github.com/Starcounter/Blending/commit/3444d16b08ec15c5e9fded29654d0da9869b20b4), with this change issue is not reproducible, but some tests are failing as well (https://teamcity.starcounter.org/viewLog.html?buildId=47959 while consequent build on master is full green). 

On my view, the current issue is really a side-effect of https://github.com/Starcounter/Blending/pull/3/.
Despite the fact that the explanation from Anton was quite voluminous, I still can not say that I am now expert with this part of CompositionProvider code and logic.

@warpech could you please clarify: next step for this issue should be the more correct fix for that line with which all tests will be green?

**Comment by warpech** [comment]
People app is not really needed to reproduce this problem. I have simplified the steps to reproduce.

-------

This solution https://github.com/Starcounter/Blending/commit/3444d16b08ec15c5e9fded29654d0da9869b20b4 not correct for two reasons:

1. it must be conditional. See the quote from the comment few lines above:

> When the JSON subtree is for a layout, BlendingProvider_0 = layout, BlendingProvider_1 = composition. In other cases, BlendingProvider_0 = composition.

2. if you hardcode `BlendingProvider_1 ` it still does not work because there is no `Compositon$` in `BlendingProvider_1` at this JSON subtree.

-------

Now we get to the real problem.

The problem is that none of the `BlendingProvider_*` responses at this level in JSON has `Composition$`.

![image](https://user-images.githubusercontent.com/566463/36729704-5e0dfd58-1bc5-11e8-91e2-ece446bf37c8.png)

This level in JSON is provided by ViewKeeper for caching reasons. It cannot have compositions of its own.

The blending point `starcounter-include[slot="blendingeditor/Main"]` should not even be presented in the composition editor dropdown, because the view-model at this level does not have a composition provider (= does not have a `BlendingProvider_*` subtree with `Composition$` property). 

@kegor can you make an issue for that?

------

The code in `/src/BlendingProvider/Composition/Api/Middleware.cs` should be switched to be more flexible to avoid such misunderstandings in future.

```js
(function () {
    const constructor = customElements.get('starcounter-include');
    if (typeof constructor !== 'undefined') {
        Object.defineProperty(constructor.prototype, 'compositionProvider', { 
            get: function() {
                const keys = Object.keys(this.partial);
                const compositionProviderKey = keys.find((key) => {
                    return key.startsWith('BlendingProvider_') && this.partial[key].hasOwnProperty('Composition$');
                });
                return compositionProviderKey; //returns the key of the composition provider or undefined if not found
            }
        });
    }
})()
```

@kegor can you make a PR for that?

**Comment by tomalec** [comment]
>  should be switched to be more flexible to avoid such misunderstandings in future.

Are you sure it won't affect performance for solutions with many apps and nested views?

**Comment by warpech** [comment]
> Are you sure it won't affect performance for solutions with many apps and nested views?

It will affect performance, but I can't propose a better solution to the problem.

**Comment by tomalec** [comment]
> Right now starcounter-include assumes that there always is a composition provider in the partial view-model.

In case there is no `BlendingProvider` running your fix does not change that.
In case BlendingProvider is running, personally, I think it should always have a composition.

**Comment by tomalec** [comment]
> Right now starcounter-include assumes that there always is a composition provider in the partial view-model.

In case there is no `BlendingProvider` running your fix does not change that.
In case BlendingProvider is running, personally, I think it should always have a composition.

The above fix suggests that the BlendingProvider - the app that provides compositions, does not know when it provides a composition and makes `starcounter-include` check it every time, for every partial in run-time. I think it's really bad idea to delegate such responsibility to the front-end.

**Comment by warpech** [comment]
The case when BlendingProvider does not include compositions is on the level of ViewKeeper, which is used for client-side caching. We should check if that level can use `imported-template` instead of `starcounter-include`. That would solve the problem.

**Comment by tomalec** [comment]
So Blending app is aware of where it changes the place to lookup. Then it should forward it to the instance. So `sc-include` will not have to check it over and over again.

Like:
```html
<script>
scIncludeInstance.CompositionProvider = "SomethingExceptional";
</script>
or
<starcounter-include composition-provider="~">
```
