### ISSUE TITLE
⏰InvalidCastException: Unable to cast object exception

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#31]
### Steps to reproduce
1. Run Blending app.
2. Call `/BlendingEditor/resetdata`
3. Go to `/BlendingEditor/routing`
4. Select route for TopbarSurface and `Disable` it.
5. Go back to surfaceGroups and select TopbarSurface.
6. Go to routes tab.
7. Select previously disabled route and try to enable it again.
### Expected result
Checkbox should be unchecked and You should be able to save progress.
### Actual result
Exception will raise:
```
System.InvalidCastException: Unable to cast object of type 'BlendingEditor.Website.ViewModels.RoutingPage' to type 'BlendingEditor.Website.ViewModels.AllRoutesPage'.
   at lambda_method(Closure , RoutingItemPage )
   at lambda_method(Closure , Json , Input`1 )
   at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 262
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 284
   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.ParseAndProcess(TBool property, Json parent, String valueStr) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 74
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter\TransactionManager.cs:line 552
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter\Transaction.cs:line 225
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 69
   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 38
   at Starcounter.XSON.JsonPatch.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection, JsonPatchStatus previousStatus) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 599
   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 493
   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 414
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 73
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 290
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-12991\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 795
HResult=-2147467262
```

It seems like there is some uncorrect/unnecessary casting during changing something in route from All routes view.

**Comment by PatrykSzwer** [comment]
After investigation turns out that the reason of this issue, lays in authorization library and same child view-model used in two parent view-models (AllRoutesPage and RouginPage use RoutingItemPage as a view-model of one route).

A solution for that is complicated and it will take some time for @joozek78 to implement it in AuthLibrary. Before that We agreed that temporary, ugly-but-working solution, will be to duplicate RoutingItemPage view-model, for AllRoutesPage and RoutingPage to use it separately.

**Comment by warpech** [comment]
Can you please make an issue for this problem in the Authorization library?

**Comment by PatrykSzwer** [comment]
I've created issue in Authorization library: https://github.com/Starcounter/authorization/issues/66

Since #43 is merged, I'll close this for now, and reopen after https://github.com/Starcounter/authorization/issues/66 is done.

**Comment by un-tone** [comment]
@PatrykSzwer maybe better to create an issue for that in advance (instead of tracking and reopening this one)?

**Comment by PatrykSzwer** [comment]
You know what? Sure, why not. Link to related issue: https://github.com/Starcounter/Blending/issues/54

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Blending/releases/tag/5.2.0
- published in the App Warehouse
