### ISSUE TITLE
Exception when the observed folder is deleted on disk

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#334]
Copied from https://github.com/Starcounter/Blending/pull/331#pullrequestreview-175305135:

---

Code looks fine except one thing that I mentioned below.

One problem though. I wanted to test this `Recreate files from database` feature and I accidentally found a bug. When you delete the compositions folder and try to use it you will recieve an exception: 
```
starcounter.html:26 PalindromConnectionError: Server error
	System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\repositories\HeadsOmni\config\compositions\_blendingprovider_blender_layout_4cf8f70f-6a61-495f-9ee9-93c609e2c0a1_area_b0619532-5fec-4845-9019-1e26ca57a052_uri_8e7c14f5-5450-49ac-8cb5-7d28a56cd519+HomeIconPage.html'.
	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
	   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
	   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
	   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
	   at BlendingEditor.Composition.Helpers.FileSystemHelper.WriteToFileIfDifferent(String path, String content, Boolean force)
	   at BlendingEditor.Composition.Helpers.FileSystemHelper.CopyFromCacheToFile(HtmlViewComposition composition, Boolean force)
	   at BlendingEditor.Composition.Helpers.FileSystemHelper.CopyFromCacheToFiles()
	   at BlendingEditor.Website.ViewModels.SettingsPage.Handle(RecreateFilesFromDb action)
	   at lambda_method(Closure , Json , Input`1 )
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T newValue) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 340
	   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, String valueStr) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 149
	   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\tc_work\sc-19683\Level1\src\Starcounter\TransactionManager.cs:line 557
	   at Starcounter.Transaction.Scope(Action action) in C:\tc_work\sc-19683\Level1\src\Starcounter\Transaction.cs:line 233
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 38
	   at Starcounter.XSON.JsonPatch.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection, JsonPatchStatus previousStatus) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 467
	   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 361
	   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 282
	   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\tc_work\sc-19683\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 75
	   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\tc_work\sc-19683\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 290
	   at Starcounter.GatewayHandlers.<>c__DisplayClass18_1.<HandleWebSocket>b__0() in C:\tc_work\sc-19683\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 783
	   at Starcounter.Session.Use(Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\Session.cs:line 683
	   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\tc_work\sc-19683\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 782

	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
	   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
	   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
	   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
	   at BlendingEditor.Composition.Helpers.FileSystemHelper.WriteToFileIfDifferent(String path, String content, Boolean force)
	   at BlendingEditor.Composition.Helpers.FileSystemHelper.CopyFromCacheToFile(HtmlViewComposition composition, Boolean force)
	   at BlendingEditor.Composition.Helpers.FileSystemHelper.CopyFromCacheToFiles()
	   at BlendingEditor.Website.ViewModels.SettingsPage.Handle(RecreateFilesFromDb action)
	   at lambda_method(Closure , Json , Input`1 )
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T newValue) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 340
	   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, String valueStr) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 149
	   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\tc_work\sc-19683\Level1\src\Starcounter\TransactionManager.cs:line 557
	   at Starcounter.Transaction.Scope(Action action) in C:\tc_work\sc-19683\Level1\src\Starcounter\Transaction.cs:line 233
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.XSON.JsonPatch.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 38
	   at Starcounter.XSON.JsonPatch.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection, JsonPatchStatus previousStatus) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 467
	   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 361
	   at Starcounter.XSON.JsonPatch.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 282
	   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\tc_work\sc-19683\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 75
	   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\tc_work\sc-19683\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 290
	   at Starcounter.GatewayHandlers.<>c__DisplayClass18_1.<HandleWebSocket>b__0() in C:\tc_work\sc-19683\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 783
	   at Starcounter.Session.Use(Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\Session.cs:line 683
	   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\tc_work\sc-19683\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 782
```

**Comment by PatrykSzwer** [comment]
Fixed in #364
