### ISSUE TITLE
It's possible to ruin entire settings page with incorrect path

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#365]
Right now you're able to input as compositions folder path that has illegal characters which will basically block entire settings page from loading:
Example string that I put there: `.(>.!=)`

Exception:
```
PalindromConnectionError: Server error
	System.Exception: ScErrDataBindingForJsonException (SCERR14012): An exception occurred when a databinding for a property in json was used. Property 'CompositionsFolderStatus' in 'MasterWrapper.LayoutPage.Json.ViewKeeper.KeptViews.KeptViewsElement.MasterPage.SettingsPage'.
	Version: 2.4.990.191.
	Help page: https://docs.starcounter.io/?q=SCERR14012. ---> System.ArgumentException: Illegal characters in path.
	   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
	   at System.IO.Path.Combine(String path1, String path2)
	   at BlendingEditor.Composition.Helpers.FileSystemHelper.GetAbsoluteFolderPath(String relativePath)
	   at BlendingEditor.Website.ViewModels.SettingsPage.get_CompositionsFolderFullPath()
	   at BlendingEditor.Website.ViewModels.SettingsPage.get_CompositionsFolderStatus()
	   at lambda_method(Closure , Json )
	   --- End of inner exception stack trace ---
	   at lambda_method(Closure , Json )
	   at Starcounter.Templates.Property`1.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 238
	   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 444
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 323
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 300
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\tc_work\sc-19683\Level1\src\Starcounter\TransactionManager.cs:line 557
	   at Starcounter.Transaction.Scope(Action action) in C:\tc_work\sc-19683\Level1\src\Starcounter\Transaction.cs:line 233
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 452
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 323
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 292
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 452
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 323
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 292
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Json.CollectChangesForArray(Json arr, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 394
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 337
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 292
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 452
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 323
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 292
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 452
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 323
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 292
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 452
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 323
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 292
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 452
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 323
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 292
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog, Change[]& changeArr) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\JSON-Patch\ChangeLog.cs:line 102
	   at Starcounter.XSON.JsonPatch.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 128
	   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\tc_work\sc-19683\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 78
	   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\tc_work\sc-19683\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 290
	   at Starcounter.GatewayHandlers.<>c__DisplayClass18_1.<HandleWebSocket>b__0() in C:\tc_work\sc-19683\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 783
	   at Starcounter.Session.Use(Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\Session.cs:line 683
	   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\tc_work\sc-19683\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 782

	   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
	   at System.IO.Path.Combine(String path1, String path2)
	   at BlendingEditor.Composition.Helpers.FileSystemHelper.GetAbsoluteFolderPath(String relativePath)
	   at BlendingEditor.Website.ViewModels.SettingsPage.get_CompositionsFolderFullPath()
	   at BlendingEditor.Website.ViewModels.SettingsPage.get_CompositionsFolderStatus()
	   at lambda_method(Closure , Json )
	   --- End of inner exception stack trace ---
	   at lambda_method(Closure , Json )
	   at Starcounter.Templates.Property`1.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 238
	   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 444
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 323
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 300
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\tc_work\sc-19683\Level1\src\Starcounter\TransactionManager.cs:line 557
	   at Starcounter.Transaction.Scope(Action action) in C:\tc_work\sc-19683\Level1\src\Starcounter\Transaction.cs:line 233
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 452
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 323
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 292
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 452
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 323
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 292
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Json.CollectChangesForArray(Json arr, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 394
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 337
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 292
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 452
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 323
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 292
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 452
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 323
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 292
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 452
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 323
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 292
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 452
	   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 323
	   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 292
	   at Starcounter.Json.<>c__DisplayClass112_0.<ScopeAndCollectChanges>b__0() in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
	   at Starcounter.XSON.Internal.XSONInternals.RunWithinApplication(String appName, Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Internal\XSONInternals.cs:line 41
	   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog, Change[]& changeArr) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\JSON-Patch\ChangeLog.cs:line 102
	   at Starcounter.XSON.JsonPatch.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 128
	   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\tc_work\sc-19683\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 78
	   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\tc_work\sc-19683\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 290
	   at Starcounter.GatewayHandlers.<>c__DisplayClass18_1.<HandleWebSocket>b__0() in C:\tc_work\sc-19683\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 783
	   at Starcounter.Session.Use(Action action) in c:\Git\Starcounter.XSON\src\Starcounter.XSON\Sessions\Session.cs:line 683
	   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\tc_work\sc-19683\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 782
    at WebSocket._ws.onmessage (http://backoffice.omni.local:8080/sys/Palindrom/dist/palindrom-dom.min.js:14:3691)
```

**Comment by PatrykSzwer** [comment]
Closing as done.
